### ISSUE TITLE
Partial import of web-ext

### ISSUE THREAD

**Issue by northword** [northword/zotero-plugin-scaffold#10]
## 原因

1. web-ext 依赖的 addons-lint 存在依赖项警告
2. web-ext 提供了 chrome、firefox android 等的方法，不需要
3. web-ext 内建的 firefox 实例不太兼容 zotero， firefox 退出时应该会结束 extension runner，而 zotero 没有，反之亦然。

## 可能的方案

1. fork 一个 web-ext，git submodule ，打包的时候打包进去
2. 从 web-ext 重新导入 forefox 实例、rdp client，firefox extension runner ，另外实现一份 run

## 资料

- rdp 协议：https://firefox-source-docs.mozilla.org/devtools/backend/protocol.html#remote-debugging-protocol
- https://github.com/mozilla/web-ext

**Comment by windingwind** [comment]
> web-ext 内建的 firefox 实例不太兼容 zotero， firefox 退出时应该会结束 extension runner，而 zotero 没有，反之亦然。

也许可以监视zotero进程，手动结束runner。1和2不是特别要紧？

**Comment by northword** [comment]
#44
