### ISSUE TITLE
Build: prefix fluent messages only those that existed in XHTML/HTML

### ISSUE THREAD

**Issue by northword** [northword/zotero-plugin-scaffold#14]
当前是把所有的 ftl 文件里的 message 都加了前缀，不过插件模板里的其实可以不加。

但这样似乎不好判断，因为似乎也可在代码中 insert fluent 片段？所以似乎还是全加了方便一些

（而且反正现在是和模板一致了的

**Comment by northword** [comment]
我理了一下，可以看看对不对，以及需不需要把这些信息写在插件模板的自述里：

所有的 ftl message 都应有 namespace 前缀，以防止冲突，scaffold 会为所有 ftl 文件的每一条 message 都添加前缀。

对于插件模板，

- addon.ftl ，仅能在代码中使用，可以使用 `getString` 工具函数获取值，该工具函数获取且仅获取 addon.ftl 添加前缀后的值，所以不需要手动输入前缀。
- preference.ftl ，仅能在 preference.xhtml 中使用，所有 ftl 中出现过的 data-l10n-id 都会自动被 scaffold 添加前缀。

如果需要在代码中直接写 message id，需要手动为 id 指定前缀。
如果在其他 html/xhtml 中使用，无需添加前缀但是需要手动引入。

**Comment by windingwind** [comment]
> 如果需要在代码中直接写 message id，需要手动为 id 指定前缀。

这个指的是什么，我一时想不到有啥场景

**Comment by windingwind** [comment]
另外可能需要：
1. 从zotero仓库chrome/locale/en-US/zotero/mozilla 拉取自带的ftl，并对其中的ftl字符串跳过加前缀
2. 或允许用户自定义一些跳过ftl字符串加前缀的正则匹配，若命中则不加前缀且不警告

**Comment by northword** [comment]
> > 如果需要在代码中直接写 message id，需要手动为 id 指定前缀。
> 
> 这个指的是什么，我一时想不到有啥场景
> 

这种：https://github.com/windingwind/zotero-plugin-template/blob/main/src%2Fmodules%2Fexamples.ts#L277

**Comment by windingwind** [comment]
这种感觉可以增加一个`getLocaleID`函数，我改下
