### ISSUE TITLE
Replacing templates doesn't work if storing assets in a folder not called `addons`

### ISSUE THREAD

**Issue by Dominic-DallOsto** [northword/zotero-plugin-scaffold#39]
https://github.com/northword/zotero-plugin-scaffold/blob/7fd538e7f5259d1896729321392241c71ad85b75/src/lib/build.ts#L140C5-L147C8

```js
files: toArray(this.ctx.build.assets).map(
    asset => `${this.dist}/${asset}`,
)
```

This plugin stores the output build files in the `{dist}/addon/` folder but allows us to configure where these files come from by setting `ctx.build.assets`.

By default the above line searches for files at `addon/**/*.*` and maps them to the output folder by appending `{dist}/` on the front. This only works if the assets folder is called addon, so that we end up with `{dist}/addon/**/*.*`. 

If instead we change the name of the assets folder to eg. `static`, then it searches for files in `static/**/*.*` and maps them to `{dist}/static/**/*.*` instead of `{dist}/addon/**/*.*`.

I fixed this by changing the line to `${this.dist}/addon/${asset.split("/").slice(1).join("/")}`. I'm not sure if there is a dedicated path manipulation libraries that would be better to use.

**Comment by northword** [comment]
Could you try to set `src` to `[src, static]` please?

**Comment by Dominic-DallOsto** [comment]
Yeah, I set `source: ["src", "static"]` and `assets: ["static/**/*.*"]`

**Comment by northword** [comment]
Thanks for the report, I pushed a new version based on the solutions you gave.

**Comment by Dominic-DallOsto** [comment]
Thanks a lot!
