### ISSUE TITLE
如何指定输出xpi的文件名

### ISSUE THREAD

**Issue by syt2** [northword/zotero-plugin-scaffold#41]
对于支持i18n的插件名称，`__MSG_name__`

----- 

如果指定
```
defineConfig({
  ...
  name: "__MSG_name__",
  ...
})
```
则最终输出的xpi名称为`--msg-name--.xpi` （功能上没问题，但是看着不舒服），即https://github.com/northword/zotero-plugin-scaffold/blob/626a08b000f32a168c1e1c17f2c34e9166246547/src/config.ts#L61

-------

而如果指定
```
defineConfig({
  ...
  name: "XXX",
  ...
})
```
则输出的xpi插件名被写死为`XXX`，不再支持i18n

-----

不知道是否有方法指定该输出的文件名

**Comment by northword** [comment]
#42 可以提供两种方法：

1. 在 config 里指定 xpiName
2. config 里的 name 不填 `__MSG_name__`，而是填写正常的名称（这样 xpiName 看起来就正常了），当 manifest.json 存在且其中存在 name 值时，脚本不再覆盖这个属性，可以在 manifest 里填成 `__MSG_name__`，以实现本地化。（这样可能和 https://github.com/northword/zotero-plugin-scaffold/issues/31 有关）

你觉得可以接受不？

**Comment by syt2** [comment]
可以可以，感谢支持
