### ISSUE TITLE
Test profile uses default `dataDir`

### ISSUE THREAD

**Issue by sneakers-the-rat** [northword/zotero-plugin-scaffold#73]
Hello! Thanks for setting this up!!!
trying to get my tests to run locally, and i was a little concerned to see my actual zotero library in the opened zotero runner.

I traced the problem to the fact that the `extensions.zotero.dataDir` is not set in the generated `prefs.js` - if i manually set that, then it works as expected, but otherwise it will load my actual zotero library from the default data directory.

Seems like there should be an additional `data` directory created underneath `testTmp` and have that used as the dataDir - and I can see that the tester does think it's doing this, but this check seems to be incorrect: https://github.com/northword/zotero-plugin-scaffold/blob/b3a4036aa2b0ccbdd0061f84e6670d102f83d09e/src/utils/zotero-runner.ts#L86

where it only applies the supplied `dataDir` if there is one already set in the prefs (which there isn't, by default, for the tester), so that pref is ignored and not applied.

I was able to get the prefs to be created correctly if i also added this to my test config:

```js
    // ...
    prefs: {
      "extensions.zotero.dataDir": "build/testTmp/data",
    },
    // ...
```

but zotero seems to overwrite this sometime between when `prefs.js` is created and when it's launched because the `useDataDir` pref is also not set: https://github.com/zotero/zotero/blob/b806b41b6fcafdb1eac5403e5ccc801f6cf91567/chrome/content/zotero/preferences/preferences_advanced.js#L410-L414

So to get the test profile to actually use a temporary data directory and not the default data dir, i had to do this:

```js
  test: {    
    prefs: {
      "extensions.zotero.dataDir": path.resolve("build/testTmp/data"),
      "extensions.zotero.useDataDir": true,
    },
    hooks: {
      "test:bundleTests": () => {
        fs.mkdirSync(path.resolve("build/testTmp/data"), { recursive: true });
      },
    },
```

because the directory also has to be created for zotero to not get hung on a modal that prompts you to use the default data directory.

**Comment by northword** [comment]
Sorry, this may be an issue introduced by #64, please try 0.2.0-beta.10 if you still have issues?

**Comment by sneakers-the-rat** [comment]
that seems to have resolve it! thanks :)
