### ISSUE TITLE
Headless tests hang in github actions CI hangs on launching `xvfb`

### ISSUE THREAD

**Issue by sneakers-the-rat** [northword/zotero-plugin-scaffold#74]
I have gotten my tests to run locally on a non-headless zotero (which is amazing!), but i am having some trouble getting them running on CI.

I basically copied the workflow here, which seems to have run successfully 5 days ago: https://github.com/windingwind/zotero-better-notes/blob/master/.github/workflows/CI.yml

and so after some attempts at debugging mine looks very similar:

```yaml
name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: install xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb x11-xserver-utils

      - name: Install deps
        run: npm install

      - name: Test
        run: npm test

```

and my `test` command is the same: `zotero-plugin test  --abort-on-fail --exit-on-finish"`

The CI output is like this:

```
ℹ Building version 0.0.1 to /home/runner/work/weaver/weaver/build at 2024-12-18 01:43:26 in test mode.
→ Preparing static assets
→ Bundling scripts
✔ Build finished in 0.055 s.

→ Server is listening on http://localhost:34655
ℹ No local chai.js found, we recommend you install chai.js package locally.
ℹ No local mocha.js found, we recommend you install mocha.js package locally.
→ Injected 1 test files
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Could not resolve keysym XF86CameraAccessEnable
> Warning:          Could not resolve keysym XF86CameraAccessDisable
> Warning:          Could not resolve keysym XF86CameraAccessToggle
> Warning:          Could not resolve keysym XF86NextElement
> Warning:          Could not resolve keysym XF86PreviousElement
> Warning:          Could not resolve keysym XF86AutopilotEngageToggle
> Warning:          Could not resolve keysym XF86MarkWaypoint
> Warning:          Could not resolve keysym XF86Sos
> Warning:          Could not resolve keysym XF86NavChart
> Warning:          Could not resolve keysym XF86FishingChart
> Warning:          Could not resolve keysym XF86SingleRangeRadar
> Warning:          Could not resolve keysym XF86DualRangeRadar
> Warning:          Could not resolve keysym XF86RadarOverlay
> Warning:          Could not resolve keysym XF86TraditionalSonar
> Warning:          Could not resolve keysym XF86ClearvuSonar
> Warning:          Could not resolve keysym XF86SidevuSonar
> Warning:          Could not resolve keysym XF86NavInfo
Errors from xkbcomp are not fatal to the X server

 ERROR  Unable to connect to Zotero. Too many retries.


 ERROR  Error: connect ECONNREFUSED 127.0.0.1:35439
Error: connect ECONNREFUSED 127.0.0.1:35439
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
```

So it seems like we are getting stuck between the `xvfb.start` call here: https://github.com/northword/zotero-plugin-scaffold/blob/54ad99e8db68deb59f03cdc7cec117d21a02acb7/src/core/tester.ts#L560

and before the creation of the profile in the ZoteroRunner, which logs here: https://github.com/northword/zotero-plugin-scaffold/blob/7b471d29667e619f47824719bd15138e33472c75/src/utils/zotero-runner.ts#L91

since I don't see any log messages that would show up if we made it there. 

I'm not sure what could have changed between the last successful run i can see 5 days ago and now: https://github.com/windingwind/zotero-better-notes/actions/runs/12316055984/job/34375519906

but i'm raising this in case y'all had any ideas? I don't think it's related to my plugin in particular, since we don't even get to the point of trying to install it, but i could be wrong :)

I'm using `0.2.0-beta.10`.

**Comment by sneakers-the-rat** [comment]
one thing that jumps out at me is that the output lists two different ports:

```
→ Server is listening on http://localhost:34655
 ERROR  Error: connect ECONNREFUSED 127.0.0.1:35439
```

But i haven't read the implementation deeply enough to know if that's expected, and the successful test run didn't print a second port (since there wasn't an error)

**Comment by northword** [comment]
> one thing that jumps out at me is that the output lists two different ports:
> 
> ```
> → Server is listening on http://localhost:34655
>  ERROR  Error: connect ECONNREFUSED 127.0.0.1:35439
> ```
> 
> But i haven't read the implementation deeply enough to know if that's expected, and the successful test run didn't print a second port (since there wasn't an error)

This is expected, as one port is used to communicate with Mocha and one port is connected to the Firefox debugger via the Remote Debugging Protocol.

As for the error reported on CI that you mentioned, I am investigating it.

**Comment by sneakers-the-rat** [comment]
it's on a private repo but there's not a good reason i can't either invite you or make it public for the moment if that would help.

I don't think there's anything special about our plugin, though it was started with the plugin templates of ~a year ago which has weirder `esbuild` script, where we have to bundle it as an IIFE and then manually declare the bootstrap methods by doing an object destructuring like `{ install, startup, ... } = () => {}()`, but it runs fine locally on a totally fresh install so i think it's something with `xvfb` (i've had trouble getting it to run cleanly in gh actions before, so totally understandable).

Also i recognize that this is very new and explicitly beta functionality atm, so no hurry, i am extremely glad you have put this together because we were just gritting our teeth without tests and wondering if we would have to spend a week making our own custom test rig, so just trying to help out getting it on its feet because it is an *extremely* good thing to have in the plugin ecosystem.

**Comment by northword** [comment]
This seems to be caused by the system version, I noticed some time ago that the default Ubuntu version for Actions changed to 24 (yes, yesterday) [^1], whereas previously it was 22. I manually changed the version to 22 [^2] and it works successfully [^3].

I will start an investigation into the error occurring in Ubuntu 24, but I can't guarantee a time frame for a fix. It is recommended that you temporarily fix the system version of Actions to 22.

[^1]: https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#ubuntu-latest-upcoming-breaking-changes
[^2]: https://github.com/northword/zotero-format-metadata/actions/runs/12385272052/workflow#L13
[^3]: https://github.com/northword/zotero-format-metadata/actions/runs/12385272052/job/34571230322

**Comment by sneakers-the-rat** [comment]
wow amazing lol, that would have taken me a long longer to pin down. no problem pinning the version, thanks for taking the time to chase that down :)

**Comment by sneakers-the-rat** [comment]
btw would you accept a small PR for the docs both about this and running tests in general?

**Comment by northword** [comment]
> btw would you accept a small PR for the docs both about this and running tests in general?

Of course, PRs welcome.

**Comment by northword** [comment]
Fixed in #76, because GitHub Action's Ubuntu 24.04 deleted libdbus, which is the required deps for Zotero. 

Plz try 0.2.0-beta.11.

**Comment by sneakers-the-rat** [comment]
Getting this when i try and run on ubuntu 22 and 24:

```
✖ Failed to install libasound2t64. Error: Command failed: sudo apt update && sudo apt install -y libasound2t64
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
E: Unable to locate package libasound2t64
Error: Command failed: sudo apt update && sudo apt install -y libasound2t64
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
E: Unable to locate package libasound2t64
```

https://github.com/p2p-ld/kysely-zotero-dialect/actions/runs/12405255480/job/34631780969?pr=1

**Comment by northword** [comment]
Ubuntu 24.04 works fine, Ubuntu 22.04 may be fixed by https://github.com/northword/zotero-plugin-scaffold/commit/41050bd935672da9f39061d87c88141704f11c0e , please try 0.2.0-beta.12. 

Ubuntu 22.04： https://github.com/northword/zotero-format-metadata/actions/runs/12406145063/job/34634141377

Ubuntu-latest: https://github.com/northword/zotero-format-metadata/actions/runs/12406215286/job/34634323191
